#!/usr/bin/env groovy

pipeline {
    agent any
    tools {
        maven 'Maven3.9'
    }
    environment {
        DOCKER_REPO='petrdeveloper/demo-app'
    }
    stages {
        stage('increment version') {
            steps {
                dir('java-maven-app') {
                    script {
                        echo 'incrementing app version...'
                        sh 'mvn build-helper:parse-version versions:set \
                            -DnewVersion=\\\${parsedVersion.majorVersion}.\\\${parsedVersion.minorVersion}.\\\${parsedVersion.nextIncrementalVersion} \
                            versions:commit'
                        def matcher = readFile('pom.xml') =~ '<version>(.+)</version>'
                        def version = matcher[0][1]
                        env.IMAGE_NAME = "$version-$BUILD_NUMBER"
                    }
                }
            }
        }
        stage('build app') {
            steps {
                dir('java-maven-app') {
                    script {
                        echo 'building the application...'
                        sh 'mvn clean package'
                    }
                }
            }
        }
        stage('build image') {
            steps {
                dir('java-maven-app') {
                    script {
                        echo "building the docker image..."
                        withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', passwordVariable: 'PASS', usernameVariable: 'USER')]){
                            sh "docker build -t ${DOCKER_REPO}:${IMAGE_NAME} ."
                            sh 'echo $PASS | docker login -u $USER --password-stdin ${DOCKER_REPO_SERVER}'
                            sh "docker push ${DOCKER_REPO}:${IMAGE_NAME}"
                        }
                    }
                }
            }
        }
        stage('deploy') {
            environment {
                AWS_ACCESS_KEY_ID = credentials('jenkins_aws_access_key_id')
                AWS_SECRET_ACCESS_KEY = credentials('jenkins_aws_secret_access_key')
                APP_NAME = 'java-maven-app'
            }
            steps {
                dir('java-maven-app') {
                    script {
                    echo 'deploying docker image...'
                    sh 'envsubst < kubernetes/deployment.yaml | kubectl apply -f -'
                    sh 'envsubst < kubernetes/service.yaml | kubectl apply -f -'
                    }
                }
            }
        }
        stage('commit version update'){
            steps {
                dir('java-maven-app') {
                    script {
                        withCredentials([usernamePassword(credentialsId: 'github-username-token', passwordVariable: 'TOKEN', usernameVariable: 'USER')]){
                            sh "git remote set-url origin https://${USER}:${TOKEN}@github.com/pvlasak/11_DevOps_Kubernetes_on_AWS.git"
                            sh 'git add .'
                            sh 'git commit -m "ci: version bump"'
                            sh 'git push origin HEAD:jenkins_dockerhub'
                        }
                    }
                }
            }
        }
    }
}
