def gv

pipeline {   
    agent any
    tools {
        maven 'Maven3.9'
    }
    stages {
        stage("init") {
            steps {
                dir('java-maven-app') {
                    script {
                        gv = load "script.groovy"
                    }
                }
            }
        }
        stage("build jar") {
            steps {
                dir('java-maven-app') {
                    script {
                        gv.buildJar()
                    }
                }
            }
        }

        stage("build image") {
            steps {
                dir('java-maven-app') {
                    script {
                        gv.buildImage()
                    }
                }
            }
        }

        stage("deploy") {
            environment {
                AWS_ACCESS_KEY_ID = credentials('jenkins_aws_access_key_id')
                AWS_SECRET_ACCESS_KEY = credentials('jenkins_aws_secret_access_key')
            }
            steps {
                dir('java-maven-app') {
                    script {
                        gv.deployApp()
                        withKubeConfig([credentialsId: 'lke-credentials', serverUrl: 'https://d2beca60-e4ec-43fe-8afc-8c38c2b5c440.eu-central-2-gw.linodelke.net']) {
                            sh 'kubectl create deployment nginx-deployment --image=nginx'                       
                        }
                    }
                }
            }
        }               
    }
} 
