def gv

pipeline {   
    agent any
    tools {
        maven 'Maven3.9'
    }
    stages {
        stage("init") {
            steps {
                dir('java-maven-app') {
                    script {
                        gv = load "script.groovy"
                    }
                }
            }
        }
        stage("build jar") {
            steps {
                dir('java-maven-app') {
                    script {
                        gv.buildJar()
                    }
                }
            }
        }

        stage("build image") {
            steps {
                dir('java-maven-app') {
                    script {
                        gv.buildImage()
                    }
                }
            }
        }

        stage("deploy") {
            environment {
                AWS_ACCESS_KEY_ID = credentials('jenkins_aws_access_key_id')
                AWS_SECRET_ACCESS_KEY = credentials('jenkins_aws_secret_access_key')
            }
            steps {
                dir('java-maven-app') {
                    script {
                        gv.deployApp()
                        sh 'kubectl create deployment nginx-deployment --image=nginx'
                    }
                }
            }
        }               
    }
} 
